name: publish
run-name: ${{ github.actor }} is publishing stuff
on: [push]
jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'checkout'
      uses: 'actions/checkout@v4'

    - name: Retrieve theme
      run: git submodule update --init --recursive

    - name: Set up hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: "0.92.2"

    - name: Build
      run: hugo --minify

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'bpcreech-test-1'
        workload_identity_provider: 'projects/433482736901/locations/global/workloadIdentityPools/github/providers/blog'

    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: 'public'
        destination: 'www.bpcreech.com'
